audio_data:
  type: "log"
  sampling_rate: 16000
  window_size: 0.02
  window_stride: 0.01
  window: 'hamming'

model:
  type: transducer
  cnn_encoder:
    local_cnn_encoder: 
        kernel_size: 5
        stride: 1
        feature_dim: 160
        dim_out: 160
    global_cnn_encoder:
        n_layers: 3
        kernel_size_pw: 1
        kernel_size_dw: 3
        stride: 1
        input_dim: 160  
        hidden_dim: 320
        n_dropout: 0.1
    dim_out: 160
  enc:
      type: lstm
      hidden_size: 320
      output_size: 320
      n_layers: 4
      bidirectional: True
  dec:
      type: lstm
      embedding_size: 512
      hidden_size: 512
      output_size: 320
      n_layers: 2
  joint:
      input_size: 640
      inner_size: 512

  vocab_size: 4866
  feature_dim: 160
  dropout: 0.3
  name : 'conv-rnnt'
  share_weight: False
  

training:
  epochs: 100
  batch_size: 2
  save_path: "/data/npl/Speech2Text/rna/conv-rnnt/save_model/2502"
  train_path : "/data/npl/Speech2Text/rna/transformer_transducer/data/train_w2i.json"
  dev_path : "/data/npl/Speech2Text/rna/transformer_transducer/data/test_w2i.json"
  test_path : "/data/npl/Speech2Text/rna/transformer_transducer/data/test_w2i.json"
  vocab_path : "/data/npl/Speech2Text/rna/transformer_transducer/data/vocab_w2i.json"
  cmvn_stats : "/data/npl/Speech2Text/rna/zlinhtinh/cmvn_stats.pt"
  reload: True
  max_grad_norm: 200


optim:
  type: adam
  lr: 0.001
  weight_decay: 0
  decay_rate: 0.5

scheduler:
  lr_init: 0.001
  warmup_steps: 10000

rnnt_loss:
  blank: 4
  reduction: "mean" 